### ISSUE TITLE
Add support for loom atomics

### ISSUE THREAD

**Issue by Kannen** [flier/rust-atomic-traits#3]
Add support for [loom](https://crates.io/crates/loom) atomic.

Loom is widely use to test lock-free data structures. It could be great if we could use traits from this crates and use atomics from loom for testing.

But there is a difficulty. Atomic types from loom does not implement all methods of std atomic: no `get_mut`, `into_inner`, `fetch_max`, `fetch_min`.

**Comment by flier** [comment]
@Kannen Maybe you could submit a feature request to upstream `loom` crate to add those methods, or we can only remove them from all traits.
